app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

home:
  resource: "@AppBundle/Controller/HomeController"
  type: annotation
article:
  resource: "@AppBundle/Controller/Article/"
  type: annotation
  prefix: /article
